import { StyleSheet } from 'react-native';
import { type ColorPalette, DarkColors, BorderRadius, FontSizes, Spacing, withTextShadow } from '../constants/theme';

export const FONTS = { family: 'System' };

export const createStyles = (colors: ColorPalette) =>
  StyleSheet.create(withTextShadow({
    container: { flex: 1 },
    map: { flex: 1 },
    scrollView: { flex: 1 },
    stickyHeader: {
      backgroundColor: 'transparent',
      borderBottomWidth: 0,
      borderBottomColor: 'transparent',
      marginHorizontal: -Spacing.xl,
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing.lg,
    },
    stickyHeaderStuck: {
      backgroundColor: colors.background.primary,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.primary,
      marginHorizontal: -Spacing.xl,
      paddingHorizontal: Spacing.xl,
      paddingTop: Spacing.lg,
    },
    titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.lg },
    title: { fontSize: FontSizes.title, fontWeight: 'bold', fontFamily: FONTS.family, color: colors.primary },
    refreshButton: {
      position: 'absolute',
      top: -12,
      right: 0,
      zIndex: 20,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.background.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 5,
      borderWidth: 1,
      borderColor: colors.border.primary,
    },
    refreshIconSpinning: { opacity: 0.5 },
    subtitle: {
      fontSize: FontSizes.trainDate,
      fontFamily: FONTS.family,
      color: colors.secondary,
      marginTop: -Spacing.sm,
      marginBottom: Spacing.md,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.background.tertiary,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.md,
      marginBottom: Spacing.xl,
    },
    searchContainerCollapsed: { marginBottom: Spacing.md, paddingHorizontal: Spacing.sm },
    searchInput: {
      flex: 1,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      color: colors.primary,
      fontSize: FontSizes.searchLabel,
      fontFamily: FONTS.family,
    },
    frequentlyUsedSection: { marginBottom: Spacing.lg },
    sectionLabel: {
      fontSize: FontSizes.timeLabel,
      fontFamily: FONTS.family,
      color: colors.secondary,
      letterSpacing: 0.5,
      marginBottom: Spacing.md,
      fontWeight: '600',
    },
    frequentlyUsedItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.background.primary,
      borderRadius: BorderRadius.md,
      padding: Spacing.md,
      marginBottom: Spacing.sm,
      borderWidth: 1,
      borderColor: colors.border.primary,
    },
    searchButtonText: {
      flex: 1,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      color: colors.secondary,
      fontSize: FontSizes.searchLabel,
      fontFamily: FONTS.family,
    },
    frequentlyUsedIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.background.secondary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.md,
    },
    frequentlyUsedText: { flex: 1 },
    frequentlyUsedName: {
      fontSize: FontSizes.searchLabel,
      fontFamily: FONTS.family,
      color: colors.primary,
      fontWeight: '600',
      marginBottom: 2,
    },
    frequentlyUsedSubtitle: { fontSize: FontSizes.daysLabel, fontFamily: FONTS.family, color: colors.secondary },
    trainCard: {
    },
    trainLeft: { alignItems: 'center', justifyContent: 'center', marginRight: Spacing.lg, minWidth: 60 },
    daysAway: {
      fontSize: FontSizes.daysAway,
      fontWeight: 'bold',
      fontFamily: FONTS.family,
      color: colors.primary,
      lineHeight: 36,
    },
    daysLabel: {
      fontSize: FontSizes.daysLabel,
      fontFamily: FONTS.family,
      color: colors.secondary,
      marginTop: Spacing.xs,
      letterSpacing: 0.5,
    },
    trainCenter: { flex: 1 },
    trainHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: Spacing.xs },
    amtrakLogo: { width: 16, height: 16, marginRight: 3, resizeMode: 'contain' },
    trainNumber: {
      fontSize: FontSizes.trainNumber,
      fontFamily: FONTS.family,
      color: colors.primary,
      fontWeight: '600',
      marginLeft: 3,
      marginRight: Spacing.md,
    },
    trainDate: { fontSize: FontSizes.trainDate, fontFamily: FONTS.family, color: colors.secondary, marginLeft: 'auto' },
    route: {
      fontSize: FontSizes.route,
      fontWeight: '600',
      fontFamily: FONTS.family,
      color: colors.primary,
      marginBottom: Spacing.sm,
    },
    timeRow: { flexDirection: 'row', gap: Spacing.md },
    timeInfo: { flexDirection: 'row', alignItems: 'center' },
    arrowIcon: {
      width: 14,
      height: 14,
      borderRadius: 7,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: Spacing.sm,
    },
    departureIcon: { backgroundColor: colors.tertiary },
    arrivalIcon: { backgroundColor: colors.tertiary },
    timeCode: {
      fontSize: FontSizes.timeCode,
      fontFamily: FONTS.family,
      color: colors.secondary,
      marginRight: Spacing.sm,
    },
    timeValue: { fontSize: FontSizes.timeValue, fontFamily: FONTS.family, color: colors.primary, fontWeight: '500' },
    liveTrainMarker: {
      backgroundColor: colors.success,
      borderRadius: 16,
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.primary,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    realtimeBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, marginLeft: 8 },
    onTimeBadge: { backgroundColor: colors.success },
    delayedBadge: { backgroundColor: colors.error },
    realtimeBadgeText: { color: colors.primary, fontSize: 10, fontWeight: '600' },
    progressContainer: {
      backgroundColor: colors.background.secondary,
      borderRadius: BorderRadius.md,
      padding: Spacing.md,
      marginBottom: Spacing.md,
      borderWidth: 1,
      borderColor: colors.border.secondary,
    },
    progressHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.xs,
    },
    progressLabel: {
      fontSize: FontSizes.searchLabel,
      fontFamily: FONTS.family,
      color: colors.primary,
      fontWeight: '600',
    },
    progressValue: { fontSize: FontSizes.searchLabel, fontFamily: FONTS.family, color: colors.secondary },
    progressTrack: {
      height: 8,
      backgroundColor: colors.border.secondary,
      borderRadius: 999,
      overflow: 'hidden',
      marginBottom: Spacing.xs,
    },
    progressBar: { height: '100%', backgroundColor: colors.accentBlue, borderRadius: 999 },
    progressStep: { fontSize: FontSizes.daysLabel, fontFamily: FONTS.family, color: colors.secondary },
  }, colors.textShadow));

export const styles = createStyles(DarkColors);
